### PR TITLE
Create esphome_example.yaml

### PR DESCRIPTION
**Pull request by aneisch**
Add example for ESPHome

### CODE REVIEW

**Review by aamarioneta — APPROVED** [review]
have no real experience with esphome but looks plausible. any questions will be redirected to you ;).

**Comment by aneisch** [comment]
> have no real experience with esphome but looks plausible. any questions will be redirected to you ;).

Sure thing! You should check it out, it's a really great solution.

**Comment by ronaldt80** [comment]
Hi both, I tried to set this up for my Yamaha. Connected a mono 3.5mm jack plug to the wemos D1 mini, d3 and ground. However, when I put the jack into the "remote in" port the esp won't boot. Disconnecting the jack makes it boot successfully. Any thoughts/suggestions? Already tried to swap the wires but no luck so far.

I have in the past used the "remote in" port successfully with a marmitek extender and with the Logitech harmony hub so technically it should function provided I have the right codes. Could it be it pulls a low on D3 preventing boot?

**Comment by aneisch** [comment]
Referencing the "Best Pins to Use – ESP8266" chart at https://randomnerdtutorials.com/esp8266-pinout-reference-gpios/

If D3 (GPIO0) is pulled low at boot, the boot will fail. A workaround might be to define and physically change you transmitter pin number to D1 or D2.

**Comment by ronaldt80** [comment]
Thanks! That did the trick - I changed it to D4. With the codes of [devjklein](https://github.com/devjklein/yamaha-rx-v363-ir-codes) I can control my Yamaha amp in Home Assistant. Many thanks for the inspiration.

**Pull request merged**
